### ISSUE TITLE
Dependency issues on installing on Ubuntu Budgie

### ISSUE THREAD

**Issue by Jacob-Vlijm** [yursan9/budgie-caffeine-applet#10]
Installing the applet on Ubuntu Bidgie 17.10, in the meson.build file, the following lines cause dependency issues. The lines seem to be irrelevant. Removing them makes the applet install:

```
dependency('budgie-1.0', version: '>=2')
dependency('gobject-introspection-1.0', version: '>=1.51.1')
```

**Comment by yursan9** [comment]
Did you install budgie-devel package? What's the budgie version in Ubuntu 17.10?

**Comment by Jacob-Vlijm** [comment]
I installed it from here: `https://github.com/yursan9/budgie-caffeine-applet`, following the instructions in "Installation" > "Manual"

**Comment by yursan9** [comment]
Yes, and you need the program from list of requirement too.

**Comment by fossfreedom** [comment]
Those dependencies are for vala based applets to help with the build. For python based applets there are no build dependencies unless you assume python3 is not installed.

**Comment by yursan9** [comment]
Well, yes for the gobject-introspection. But it's still need to check Budgie, because Budgie.Popover need Budgie 10.4

**Comment by fossfreedom** [comment]
Not really. That is a runtime dependency. Not a build dependency.

On Wed, 25 Apr 2018, 07:33 Yurizal Susanto, <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, yes for the gobject-introspection. But it's still need to check Budgie, because Budgie.Popover need Budgie 10.4

**Comment by yursan9** [comment]
Right I forgot the applet is written in python.

**Comment by yursan9** [comment]
Can you try building this applet from branch 0.2.0, @Jacob-Vlijm?

**Comment by yursan9** [comment]
Can I close this, @Jacob-Vlijm?

**Comment by Jacob-Vlijm** [comment]
Works fin now, thanks!
