### ISSUE TITLE
The applet installs in the wrong directory on Ubuntu Budgie

### ISSUE THREAD

**Issue by Jacob-Vlijm** [yursan9/budgie-caffeine-applet#11]
On Ubuntu Budgie, applets need to be installed in  `/usr/lib/budgie-desktop/plugins`. The applet is installed in `/usr/lib/x86_64-linux-gnu/budgie-desktop/plugins/budgie-caffeine-applet`, which makes Budgie Panel mis it.

Manually moving it makes the applet show up in the available applets list.

**Comment by yursan9** [comment]
Wait a minute, how? You only change the prefix right? It should install on `/usr/lib/budgie-desktop/plugins` correctly

**Comment by yursan9** [comment]
Can you add `--libdir=lib` to meson build command?
```
meson builddir --prefix=/usr --libdir=lib
```

**Comment by Jacob-Vlijm** [comment]
Yep, that works.

**Comment by yursan9** [comment]
So, this is Ubuntu issue then. `libdir` should default to place where the package manager place library file. In Solus, it's in `lib`, so the installation path will be `/usr/lib` after prefix.

If you think this is satisfactory, can you close this issue?

**Comment by Jacob-Vlijm** [comment]
It would be an Ubuntu issue if you specifically target Solus users.  Budgie is used in a wider circle though. Might be worth adding instructions to the manual install procedure. Pretty sure Ubuntu Budgie users will try to install it.

**Comment by yursan9** [comment]
Well, the thing is manual installation is for someone who knows what they are doing, like your distro maintainers. If you like this applet and want the process for installation to be simple, you should tell the Ubuntu Budgie's maintainer to package this applet.

And it's bug in meson on Ubuntu mesonbuild/meson#2197
