### ISSUE TITLE
Caffeine applet assumes backlight, crashes if not

### ISSUE THREAD

**Issue by Jacob-Vlijm** [yursan9/budgie-caffeine-applet#12]
Trying to run it on Ubuntu Budgie 17.10, the following error occurs:

`Traceback (most recent call last):
  File "/usr/lib/budgie-desktop/plugins/budgie-caffeine-applet/budgie-caffeine-applet.py", line 215, in _on_caffeine_on
    self.defaults.get("screen-brightness"))
  File "/usr/lib/budgie-desktop/plugins/budgie-caffeine-applet/budgie-caffeine-applet.py", line 167, in change_screen_brightness
    'Brightness', value)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.gtk.GDBus.UnmappedGError.Quark._gsd_5fpower_5fmanager_5ferror.Code0: gsd-backlight-helper failed: Could not get or set the value of the backlight: No backlight devices present
`

**Comment by yursan9** [comment]
Can you change your display brightness from Gnome Control Center? It shouldn't crashes if you can change it from the Gnome Control Center

**Comment by Jacob-Vlijm** [comment]
I can't change brightness change brightness from Gnome Control Center. Shouldn't the applet check and try/except?

**Comment by yursan9** [comment]
Well, I don't think that forward. If people tried Budgie and can't change screen brightness, I guess they will try another desktop.

I'll self assign this. But I'm still in the middle of midterm exam.

**Comment by fossfreedom** [comment]
@yursan9 think on this one a bit of error trapping is required.  Not all computers have brightness controls.  The applet shouldnt fail in this scenario.  The rest of the applet functionality (disabling the screensaver) should assume to work.

**Comment by yursan9** [comment]
Yes, I just need to add try/except when calling dbus method to change the brightness

**Comment by yursan9** [comment]
Can you try building this applet from branch 0.2.0, @Jacob-Vlijm and @laskhel?

**Comment by birkanucan** [comment]
I did & it seems to be working without any issues.

**Comment by Jacob-Vlijm** [comment]
Looks good! Thanks for the effort!
