### ISSUE TITLE
Affects brightness upon activation

### ISSUE THREAD

**Issue by fn-ix** [yursan9/budgie-caffeine-applet#15]
When activated, the brightness of my laptop screen is set to the maximum level.

**Comment by yursan9** [comment]
It was intentional. You can change the behavior from Budgie Desktop Settings
![caffeine settings](https://i.imgur.com/xKbQcrX.png)

**Comment by fn-ix** [comment]
Sorry, I hadn't noticed that. Thanks! Would it be possible to add an option to the left-click menu of the applet to open that settings window?

**Comment by yursan9** [comment]
Nope, I think it's not possible. When I scrapes `budgie-desktop's` source code, there is no method to pass argument to open panel settings, it's always default to style settings.

**Comment by fn-ix** [comment]
Ok, I suppose others who've had the same problem can just find this issue here on GitHub.
