### ISSUE TITLE
Add temporary timer mode

### ISSUE THREAD

**Issue by gazny** [yursan9/budgie-caffeine-applet#3]
having a timer for caffeine to stay active for custom times.
Use case would be someone watching a movie, they would open caffeine-applet set the timer to a custom duration and after the timer caffeine will disable itself.

**Comment by yursan9** [comment]
Usually, video player already prevent blank screen or suspend on fullscreen mode.
Isn't it better if I implement #2?

**Comment by gazny** [comment]
I am saying for me sometimes Ill watch a video late at night and fall asleep, I just want to be able to watch a video set a timer and know even if I fall asleep my screen wont stay on all night till I wake up in the morning.

**Comment by yursan9** [comment]
Well, I agree that a valid use case.
I'll tag this issue as feature request.

**Comment by yursan9** [comment]
Hello @gazny, do you mind testing this applet from master?
I already commit timer feature in master branch. But, I need someone to test it first.

**Comment by gazny** [comment]
Yeah I'll look at the changes and build it

**Comment by gazny** [comment]
Works great from what I had seen, reverts back to my settings and nothing has been broken. Looks great thanks for the inclusion.
![screenshot from 2017-09-14 07 35 34](https://user-images.githubusercontent.com/19635950/30435744-616da2f6-991f-11e7-8f57-80357473a681.png)

**Comment by yursan9** [comment]
Great! I need to update translation before closing this issue
