### ISSUE TITLE
Not working with latest Budgie

### ISSUE THREAD

**Issue by barabadzhi** [yursan9/budgie-caffeine-applet#8]
Hi there! ✋

Thanks for your handy applet. 🆒

I can't figure out the way to use your applet on up-to-date Solus system. 😕
Can not find an entry for it in "Applets" list in settings.

Can you update an applet to fix this, please❓

**Comment by yursan9** [comment]
Thank you for bringing this issue to me! I'll need to check this out first.
Please remind me, if I didn't update this applet in a week.

Thanks for the kind words too!

**Comment by yursan9** [comment]
Hello @barabadzhi, I can't replicate your issue in my machine. Can you provide some screenshot? Or maybe tried to reinstall this applet, and don't forget to restart after that too.
![Applets](https://i.imgur.com/WwlXYmk.png)

**Comment by barabadzhi** [comment]
Ah, man! 🐙 

Sorry, I'm new to Budgie. 👶 

Didn't know restart/logout is needed  for it to catch up applets. 😕 

All is working fine. I'm closing this.

Thanks! 🙂 👍
