### ISSUE TITLE
Single-click activation

### ISSUE THREAD

**Issue by fn-ix** [yursan9/budgie-caffeine-applet#9]
Hi!

It would be more convenient if the applet could somehow be activated with a single click, without having to locate & click the button in the popup. Could one of the mouse buttons be assigned to this end?

**Comment by yursan9** [comment]
Actually it's quite easy to implement. We can use middle mouse button to activate the applet.

But I'm in the middle of midterm exam right now. I'll try to implement this later.

**Comment by fn-ix** [comment]
Thank you, but could either the left or right mouse button be used instead? That would make it easier on touchpads. :)

**Comment by yursan9** [comment]
I'm thinking of UX, usually left click means activation and right click is for menu. So the remaining middle click buttons are never used.

On touchpad, to simulate the middle click, you can use the three finger touch or click the left and right buttons simultaneously.

**Comment by yursan9** [comment]
Closing with b60607b51d347b4e570efe0e0bdd2f49519f4cb7
